#linting , SAST Scan and testing workflow for the flask app
name: Code Quality

on:
    workflow_call

jobs:
    code-quality:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: 3.12

            - name: install dependencies
              run: pip install -r requirements.txt
              
            - name: run linter
              run: flake8 app.py
              
            - name: run SAST scan
              run: bandit -r app.py
              
            - name: run tests
              run: pytest app.py  