# this will deploy the safe / secure / tested app to the prod server

name: Deploy to Server

on:
    workflow_call:


jobs:
    deploy-to-server:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout code
              uses: actions/checkout@v4


            - name: SSH to prod server and create app folder and install required packages
              uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{ vars.SSH_HOST }}
                username: ${{ vars.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                    echo "Installing required packages & folders"
                    mkdir -p /app
                    cd /app
                    sudo apt update -y
                    sudo apt install docker.io docker-compose-v2 -y
                    sudo usermod -aG docker $USER

            - name: Copy docker-compose file to prod server
              uses: appleboy/scp-action@v1.0.0
              with:
                host: ${{ vars.SSH_HOST }}
                username: ${{ vars.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                source: "Docker-compose.yml"
                target: "/app/"
                
            - name: SSH to prod server & run the app using docker compose
              uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{ vars.SSH_HOST }}
                username: ${{ vars.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                    echo "Deploying the app using docker compose"
                    cd /app
                    docker compose down && docker compose up -d --build --force-recreate --pull always    
