# API Keys , Sensitive Data , credentials , secrets should never be hard coded in the codebase. They should be stored securely and accessed through environment variables or secret management tools.

name: Secrets Scan

on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0          # fetch-depth: 0 is required to scan full history

            - name: run gitleaks scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for the action to comment on PRs and create issues when leaks are found and this variable is automatically assigned by GitHub when any action gets kicked off.
                # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Required for Organizations only 


              